plugins:
  - jekyll-sitemap
  
headers:
  - name: Strict-Transport-Security
    value: max-age=31536000; includeSubDomains; preload
  - name: X-Frame-Options
    value: SAMEORIGIN
  - name: X-Content-Type-Options
    value: nosniff
  - name: Referrer-Policy
    value: strict-origin-when-cross-origin
  - name: Content-Security-Policy
    value: "default-src 'self'; script-src 'self' 'unsafe-inline' https://www.googletagmanager.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:;"
